// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRkVbe7VJ5rpnwhgf64dacnk7L7wtSJUg',
    appId: '1:426672758322:web:6df79fa66b2b34f79da62b',
    messagingSenderId: '426672758322',
    projectId: 'teamzoneapp',
    authDomain: 'teamzoneapp.firebaseapp.com',
    storageBucket: 'teamzoneapp.firebasestorage.app',
    measurementId: 'G-5HFGB91QXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAcgDPyW5J_3Am52N9_ZEPNOaD-u_0H0c',
    appId: '1:426672758322:android:b74c89e683cf01209da62b',
    messagingSenderId: '426672758322',
    projectId: 'teamzoneapp',
    storageBucket: 'teamzoneapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwiSGJTJjdobXlaKeyTatUSbu1bxk4HOQ',
    appId: '1:426672758322:ios:b024293211d9db599da62b',
    messagingSenderId: '426672758322',
    projectId: 'teamzoneapp',
    storageBucket: 'teamzoneapp.firebasestorage.app',
    iosBundleId: 'com.example.teamzoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwiSGJTJjdobXlaKeyTatUSbu1bxk4HOQ',
    appId: '1:426672758322:ios:b024293211d9db599da62b',
    messagingSenderId: '426672758322',
    projectId: 'teamzoneapp',
    storageBucket: 'teamzoneapp.firebasestorage.app',
    iosBundleId: 'com.example.teamzoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRkVbe7VJ5rpnwhgf64dacnk7L7wtSJUg',
    appId: '1:426672758322:web:87af63ec0e0047d29da62b',
    messagingSenderId: '426672758322',
    projectId: 'teamzoneapp',
    authDomain: 'teamzoneapp.firebaseapp.com',
    storageBucket: 'teamzoneapp.firebasestorage.app',
    measurementId: 'G-GW8TTFYC1C',
  );
}
